
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ChiTietDonHang
{

    public int id { get; set; }

    public Nullable<int> idDonHang { get; set; }

    public Nullable<int> idSanPham { get; set; }

    public Nullable<int> GiaSanPham { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }



    public virtual DonHang DonHang { get; set; }

}

}
