
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DonHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DonHang()
    {

        this.ChiTietDonHang = new HashSet<ChiTietDonHang>();

    }


    public int id { get; set; }

    public Nullable<int> idNguoiMua { get; set; }

    public Nullable<int> TongSoLuongSp { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<int> ThanhTien { get; set; }

    public Nullable<int> idTinhTrang { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }

}

}
