
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GioHang
{

    public int id { get; set; }

    public Nullable<int> idSp { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<int> IdTinhtrang { get; set; }

    public Nullable<int> KieuGiaoHang { get; set; }

    public Nullable<int> KieuThanhToan { get; set; }



    public virtual SanPham SanPham { get; set; }

}

}
