
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LoaiSp
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiSp()
    {

        this.SanPham = new HashSet<SanPham>();

    }


    public int id { get; set; }

    public Nullable<int> IdDM { get; set; }

    public string ChiTiet { get; set; }

    public string MoTa { get; set; }



    public virtual DanhMucSp DanhMucSp { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SanPham> SanPham { get; set; }

}

}
