

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web2.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class WebDoTreEmEntities2 : DbContext
{
    public WebDoTreEmEntities2()
        : base("name=WebDoTreEmEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Account> Account { get; set; }

    public virtual DbSet<DacDiemSP> DacDiemSP { get; set; }

    public virtual DbSet<DanhMucSp> DanhMucSp { get; set; }

    public virtual DbSet<GioHang> GioHang { get; set; }

    public virtual DbSet<HinhAnhChiTietSp> HinhAnhChiTietSp { get; set; }

    public virtual DbSet<LoaiSp> LoaiSp { get; set; }

    public virtual DbSet<NhomQuyen> NhomQuyen { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<PhuongXa> PhuongXa { get; set; }

    public virtual DbSet<QuanHuyen> QuanHuyen { get; set; }

    public virtual DbSet<Quyen> Quyen { get; set; }

    public virtual DbSet<RoleAccount> RoleAccount { get; set; }

    public virtual DbSet<SanPham> SanPham { get; set; }

    public virtual DbSet<Size> Size { get; set; }

    public virtual DbSet<SpBySize> SpBySize { get; set; }

    public virtual DbSet<TinhThanh> TinhThanh { get; set; }

    public virtual DbSet<TinhTrangDonHang> TinhTrangDonHang { get; set; }

    public virtual DbSet<ThongTinGiaoHang> ThongTinGiaoHang { get; set; }

}

}

