
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SanPham
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SanPham()
    {

        this.HinhAnhChiTietSp = new HashSet<HinhAnhChiTietSp>();

    }


    public int Id { get; set; }

    public string Masp { get; set; }

    public string TenSanPham { get; set; }

    public string MotaSp { get; set; }

    public string AnhSp { get; set; }

    public Nullable<int> Gia { get; set; }

    public Nullable<int> GiamGia { get; set; }

    public string TinhTrang { get; set; }

    public Nullable<int> HotSearch { get; set; }

    public Nullable<int> IdLoai { get; set; }

    public int IdDanhMuc { get; set; }

    public string GhiChu { get; set; }

    public string Brand { get; set; }

    public string MauSP { get; set; }

    public string Sizesp_soLuong { get; set; }

    public string SoLuong { get; set; }

    public string AnhChiTiet { get; set; }

    public string DacDiemNB { get; set; }



    public virtual DanhMucSp DanhMucSp { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HinhAnhChiTietSp> HinhAnhChiTietSp { get; set; }

    public virtual LoaiSp LoaiSp { get; set; }

}

}
