//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thongtinthem
    {
        public int id { get; set; }
        public Nullable<int> IDSp { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> Ghichu { get; set; }
        public Nullable<int> SoLuongBanDuoc { get; set; }
        public Nullable<int> HotTrend { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
