
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ThongTinGiaoHang
{

    public int id { get; set; }

    public Nullable<int> idUser { get; set; }

    public string HoVaTen { get; set; }

    public string Email { get; set; }

    public string SoDienThoai { get; set; }

    public string DiaChi { get; set; }

    public Nullable<int> idTinhThanh { get; set; }

    public Nullable<int> idQuanHuyen { get; set; }

    public Nullable<int> idPhuongXa { get; set; }



    public virtual Account Account { get; set; }

}

}
